name: Cross-Platform CMake Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake 3.22.1 on Linux
        run: |
          wget https://cmake.org/files/v3.22/cmake-3.22.1-Linux-x86_64.tar.gz
          tar -xzvf cmake-3.22.1-Linux-x86_64.tar.gz
          sudo cp -r cmake-3.22.1-Linux-x86_64/* /usr/local/
        shell: bash

      - name: Install dependencies
        run: |
          chmod +x install_deps.sh
          ./install_deps.sh
        shell: bash

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Build
        run: cmake --build build --config Release
        shell: bash

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies on Windows
        run: |
          choco install glfw3 zeromq sqlite googletest -y
        shell: pwsh

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        shell: pwsh

      - name: Build
        run: cmake --build build --config Release
        shell: pwsh
